### ISSUE TITLE
storing images in DB as blobs

### ISSUE THREAD

**Issue by iks-github** [iks-github/Fileman#43]
Currently, images are stored a Base64 encoded string values which only allows a storage of small images. This prototype handling must be replaced by an image handling that allows storing of huge images. Images (for files and user avatars) must be stored in the database as blobs.

**Comment by ascIKS** [comment]
The file content data are now stored as BLOBs. Avatars are currently stored as CLOBs, as currently the file type differentiation in the frontend works with the String prefix. If wanted/needed, we could also change the avatars to BLOBs, or we could leave them as CLOBs. BLOBs and CLOBs are generally equivalent; the only difference is that BLOBs are stored as binary data and CLOBs as String data.
